export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const RECEIVE_TODOS = "RECEIVE_TODOS";
export const REQUEST_TODOS = "REQUEST_TODOS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";
